version: "3"

services:
  postgres:
    image: postgres:alpine
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=pass
    user: root
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - .:/var/lib/postgres/data

volumes:
  postgres:
    external: false
